app/models/Voto.py
from app import db
from app import ma

class Voto(db.Model):
    __tablename__ = 'voto'
    id_voto = db.Column(db.Integer, primary_key=True, autoincrement=True)
    id_elector = db.Column(db.Integer, db.ForeignKey('elector.id'), nullable=True)
    id_lista = db.Column(db.Integer, db.ForeignKey('lista_candidato.id_lista'), nullable=True)

    def __init__(self, id_elector, id_lista):
        self.id_elector = id_elector
        self.id_lista = id_lista

class VotoSchema(ma.Schema):
    class Meta:
        fields = (
            'id_voto',
            'id_elector',
            'id_lista'
        )

app/routes/routes.py
import logging
from functools import wraps
from flask import render_template, Blueprint, request, jsonify, session, redirect, url_for, make_response, flash, abort
from flask_login import login_user, logout_user, login_required, login_manager

from app.services.PersonaServicioImpl import ElectorServiceImpl
from app.services.EleccionServicioImpl import EleccionServicioImpl
from app.services.EleccionServicioImpl import ListaServicioImpl
from app.services.EleccionServicioImpl import CandidatoServicioImpl
from app.services.EleccionServicioImpl import VotoServicioImpl

from app.models.Elector import Elector
from app.models.Eleccion import Eleccion
from app.models.ListaCandidato import ListaCandidato
from app.models.Candidato import Candidato
from app.models.Propuesta import Propuesta

from functools import wraps
from app.services.PersonaServicioImpl import ElectorServiceImpl
from app.services.EleccionServicioImpl import EleccionServicioImpl


from dotenv import load_dotenv
import os

load_dotenv()

import bcrypt

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

REGISTER_TEMPLATE = 'register.html'

LOGIN_ROUTE = 'home_bp.login'

home_bp = Blueprint('home_bp', __name__, template_folder='templates')

elector_service = ElectorServiceImpl()
eleccion_servicio = EleccionServicioImpl()
lista_servicio = ListaServicioImpl()
candidato_servicio = CandidatoServicioImpl()
voto_servicio = VotoServicioImpl()

def admin_required(f):
    @wraps(f)
    def decorated_function_admin(*args, **kwargs):
        logger.info(f"Verificando acceso: sesión actual {session}")
        if not session.get('admin'):
            logger.info(f"Usuario no autorizado, sesión: {session}")
            return render_template("login.html")  
        return f(*args, **kwargs)
    return decorated_function_admin

@home_bp.route('/Admins')
@admin_required
def home():
    return render_template('Admin/home.html')


@home_bp.route('/ListaElecciones', methods=['GET'])
def mostrar_elecciones():
    eleccionesf = eleccion_servicio.get_elecciones_past()
    eleccionescurso = eleccion_servicio.get_elecciones_en_curso()
    eleccionespro = eleccion_servicio.get_elecciones_futuras()
    return render_template('General/elecciones.html', eleccionespro=eleccionespro, eleccionesf=eleccionesf, eleccionescurso=eleccionescurso)


@home_bp.route('/ListasCandidatos', methods=['GET'])
def listar_candidatos():
    listas_json = lista_servicio.obtener_listas()
    return render_template('ListaCandidato/lista_candidatos.html', listas=listas_json)

@home_bp.route('/aprobar_lista/<int:id_lista>', methods=['PUT'])
def aprobar_lista(id_lista):
    try:
        lista_servicio.aprobar_lista(id_lista)
        return jsonify({'message': 'Lista aprobada exitosamente'}), 200
    except Exception as e:
        logger.error(f'Error al aprobar la lista: {str(e)}')
        return jsonify({'message': 'Error al aprobar la lista', 'error': str(e)}), 500

@home_bp.route('/desaprobar_lista/<int:id_lista>', methods=['PUT'])
def desaprobar_lista(id_lista):
    try:
        lista_servicio.desaprobar_lista(id_lista)
        return jsonify({'message': 'Lista desaprobada exitosamente'}), 200
    except Exception as e:
        logger.error(f'Error al desaprobar la lista: {str(e)}')
        return jsonify({'message': 'Error al desaprobar la lista', 'error': str(e)}), 500

def login_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if 'correo' not in session:
            return redirect(url_for(LOGIN_ROUTE))
        return f(*args, **kwargs)
    return decorated_function


@home_bp.route('/ListasEleccionesVista', methods=['GET'])
def listar_candidatos_elector():
    listas = lista_servicio.obtener_listas_aprobadas()
    return render_template('ListaCandidato/listas_aprobadas.html', listas = listas)

@home_bp.route('/ListasElecciones', methods=['GET'])
def listas_candidatos_elector():
    listas = lista_servicio.obtener_listas_aprobadas()
    return render_template('ListaCandidato/listas_aprobadas.html', listas = listas)



@home_bp.route('/EleccionesActivas', methods=['GET'])
def listar_elecciones():
    elecciones_json = eleccion_servicio.get_all_eleccion()
    return render_template('lista_eleccion.html', elecciones = elecciones_json)


@home_bp.route('/candidatos/<int:id>', methods=['GET'])
def ver_lista_candidatos(id):
    listas_candidato = lista_servicio.get_lista_por_eleccion(id)

    if listas_candidato is None:
        abort(404)
    return render_template('ListaCandidato/lista_candidatos.html', listas=listas_candidato)

@home_bp.route('/VerListas', methods=['GET'])
def ver_candidatos():
    candidatos = candidato_servicio.get_candidatos_inscritos()
    return render_template("ListaCandidato/candidatos_inscritos.html", candidatos = candidatos)

@home_bp.route('/FormularioEleccion', methods=['GET'])
def agregar_eleccion():
    return render_template("ProcesoVotacion/form_eleccion.html")

@home_bp.route('/InsertEleccion', methods=['POST'])
def insert_eleccion():
    fecha = request.form['fecha']
    hora_inicio = request.form['hora_inicio']
    hora_fin = request.form['hora_fin']
    estado = request.form['estado']
    descripcion = request.form['descripcion']
    eleccion = Eleccion(fecha, hora_inicio, hora_fin, estado, descripcion)
    eleccion_servicio.insert_eleccion(eleccion)
    return url_for('home_bp.home')

@home_bp.route('/Votos')
def ver_votos():
    elecciones = eleccion_servicio.get_all_elecciones()
    votos = {}
    for eleccion in elecciones:
        votos[eleccion['id_eleccion']] = voto_servicio.get_cant_votos_by_eleccion(eleccion['id_eleccion'])
    print(len(votos))
    return render_template("ProcesoVotacion/votos.html", data = votos, elecciones = elecciones)


@home_bp.route('/EleccionVotacion', methods=['GET'])
@login_required
def seleccionar_eleccion_votacion():
    elector = elector_service.get_elector_by_email(session['correo'])
    elecciones = eleccion_servicio.get_elecciones_en_curso()
    elecciones_hechas = eleccion_servicio.get_elecciones_hechas_por_elector(elector.id)
    elecciones_restantes = len(elecciones) - len(elecciones_hechas)
    return render_template('ProcesoVotacion/lista_eleccion_votacion.html', \
                           data = elecciones, elecciones_hechas = elecciones_hechas, \
                            elecciones_restantes = elecciones_restantes)

@home_bp.route('/ListaVotacion', methods=['POST'])
@login_required
def ver_candidatos_votacion():
    id_eleccion = request.form['voto']
    candidatos = lista_servicio.get_lista_aprobada_by_eleccion(id_eleccion)
    print(candidatos)
    return render_template('ProcesoVotacion/votacion.html', data = candidatos)

@home_bp.route('/Resumen', methods=['POST'])
@login_required
def resumir_votacion():
    id_lista = request.form['id_lista']
    lista = lista_servicio.get_lista_by_id(id_lista)
    return render_template('ProcesoVotacion/resumen.html', data = lista)

@home_bp.route('/Votar', methods=['POST'])
@login_required
def votar():
    id_lista = request.form['id_lista']
    elector = elector_service.get_elector_by_email(session['correo'])
    voto_servicio.votar(id_lista, elector.id)
    return redirect(url_for('home_bp.dashboard'))

@home_bp.route('/')
def index():
    return render_template('index.html')

@home_bp.route('/register', methods=['GET','POST'])
def register():
    REGISTER_HTML = 'register.html'
    try:
        if request.method == 'POST':
            data = request.form
            elector = Elector(
                nombres=data.get('nombres'),
                apellido_paterno=data.get('apellido_paterno'),
                apellido_materno=data.get('apellido_materno'),
                fecha_nacimiento=data.get('fecha_nacimiento'),
                usuario=data.get('usuario'),
                contrasena=data.get('contrasena'),
                correo=data.get('correo')
            )

            elector_service.create_elector(elector,data.get('contrasena'))
            mensaje = 'Elector creado correctamente'
            return render_template(REGISTER_HTML, mensaje=mensaje)

        return render_template(REGISTER_HTML)
    except Exception as e:
        mensaje_error = f"Error al crear el elector: {str(e)}"
        logger.error(mensaje_error)
        return render_template(REGISTER_HTML, mensaje=mensaje_error)

@home_bp.route('/login', methods=['GET','POST'])
def login():
    LOGIN_HTML = 'login.html'
    try:
        if request.method == 'POST':
            data = request.form
            correo = data.get('correo')
            contrasena = data.get('contrasena')
            admin_email = os.getenv('ADMIN_EMAIL')
            admin_password = os.getenv('ADMIN_PASSWORD')
            if correo == admin_email and bcrypt.checkpw(contrasena.encode('utf-8'), admin_password.encode('utf-8')):
                session['correo'] = admin_email
                session['admin'] = True
                return render_template('Admin/home.html')
            elector = Elector.query.filter_by(correo=correo).first()
            if elector is None:
                mensaje = 'Correo o contraseña incorrectos'
                return render_template(LOGIN_HTML, mensaje=mensaje)
            if elector and elector.revisar_contrasena(contrasena):
                session['correo'] = elector.correo
                logger.info(f'El elector {elector.nombres} ha iniciado sesión')
                return render_template('dashboard.html', elector=elector)
            else:
                mensaje = 'Correo o contraseña incorrectos'
                return render_template(LOGIN_HTML, mensaje=mensaje)
        return render_template(LOGIN_HTML)
    except Exception as e:
        mensaje_error = f"Error al iniciar sesión: {str(e)}"
        logger.error(mensaje_error)
        return render_template(LOGIN_HTML, mensaje=mensaje_error)

@home_bp.route('/dashboard')
@login_required
def dashboard():
    if 'correo' in session:

app/templates/ProcesoVotacion/form_eleccion.html
{% extends "base.html" %}
{% block title %}Listas de Elecciones activas{% endblock %}

{% block content %}
    <h1>Ingrese los siguientes datos:</h1>
    <form action="{{ url_for('home_bp.home') }} method="POST">
        <label for="fecha">Fecha:</label>
        <input type="date" id="fecha" name="fecha" required><br><br>
    
        <label for="hora_inicio">Hora de inicio:</label>
        <input type="time" id="hora_inicio" name="hora_inicio" required><br><br>
    
        <label for="hora_fin">Hora de fin:</label>
        <input type="time" id="hora_fin" name="hora_fin" required><br><br>
    
        <label for="estado">Estado:</label>
        <select id="estado" name="estado" required>
            <option value="abierto">Abierto</option>
            <option value="cerrado">Cerrado</option>
        </select><br><br>
    
        <label for="descripcion">Descripción:</label><br>
        <textarea id="descripcion" name="descripcion" rows="4" cols="50" required></textarea><br><br>
    
        <input type="submit" value="Submit">
    </form>
{% endblock %}

app/templates/ProcesoVotacion/lista_eleccion_votacion.html
{% extends "base.html" %}
{% block title %}Detalles de la Elección{% endblock %}
{% block head %}
<style>
    body {
        background-color: #f0f0f0;
    }
    .container {
        margin-top: 50px;
        padding: 20px;
        background-color: #ffffff;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }
    .candidate {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 15px;
        border: 1px solid #007bff;
        border-radius: 10px;
        margin-bottom: 20px;
        transition: background-color 0.3s;
    }
    .candidate:hover {
        background-color: #e9ecef;
    }
    .candidate div {
        flex: 1;
        text-align: center;
    }
    .candidate img {
        max-width: 100px;
        border-radius: 50%;
    }
    .emitir-voto {
        background-color: #007bff;
        border-color: #007bff;
        color: white;
        padding: 10px 20px;
        width: 100%;
        border-radius: 10px;
        transition: background-color 0.3s, border-color 0.3s;
    }
    .emitir-voto:hover {
        background-color: #0056b3;
        border-color: #004085;
    }
    .emitir-regresar{
        background-color: #596169;
        border-color: #18191a;
        color: white;
        padding: 10px 20px;
        width: 100%;
        border-radius: 10px;
        transition: background-color 0.3s, border-color 0.3s;
    }
    .emitir-regresar:hover {
        background-color: #596169;
        border-color: #18191a;
    }

</style>
{% endblock %}
{% block content %}
<body>
    <h3>Elija la eleccion en la que participara:</h3>
    <div class="container">
        <form id="votingForm" action="{{ url_for('home_bp.ver_candidatos_votacion') }}" method="post">
            {% for eleccion in data %}
            <div class="candidate">
                <div id="nombre-eleccion">
                    <h5>{{ eleccion.descripcion }} </h5>
                </div>
                <div id="nombre-partido">
                    <h5>Fechas:</h5>
                    <p>Inicio: {{ eleccion.hora_inicio }} </p>       
                    <p>Fin:  {{ eleccion.hora_fin }} </p>
                </div>
                {% if eleccion.id_eleccion not in elecciones_hechas %}
                <div class="option">
                    <input type="radio" name="voto" id="{{ eleccion.id_eleccion }}" value="{{ eleccion.id_eleccion }}">
                </div>
                {% else %}
                <div class="option">
                    <h5>Usted ya voto en esta eleccion</h5>
                </div>
                {% endif %}
            </div>
            {% endfor %}
            {% if elecciones_restantes != 0 %}
            <button type="submit" class="btn btn-primary emitir-voto">Continuar con la votación</button>
            <a class="btn btn-primary emitir-voto" href="{{ url_for('home_bp.dashboard') }}" >Ir a Dashboard</a>

            {% else %}
            <h5>Usted ya voto en todas las elecciones</h5>
            <a href="{{ url_for('home_bp.dashboard') }}" class="btn btn-primary">Ir a dashboard</a>
            {% endif %}
        </form>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script>
        document.getElementById('votingForm').addEventListener('submit', function(event) {
            const radios = document.querySelectorAll('input[name="voto"]');
            let isChecked = false;
            radios.forEach(radio => {
                if (radio.checked) {
                    isChecked = true;
                }
            });
            if (!isChecked) {
                event.preventDefault();
                alert('Por favor seleccione una elección antes de continuar.');
            }
        });
    </script>
</body>

{% endblock %}

app/templates/ProcesoVotacion/prueba.html
{% extends "base.html" %}
{% block title %}Detalles de la Elección{% endblock %}

{% block content %}
    <h2>Candidatos</h2>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Candidato</th>
                <th>Lista</th>
            </tr>
        </thead>
        <tbody>
            {% for candidato in data %}
            <tr>
                <td>{{ candidato.Candidato }}</td>
                <td>{{ candidato.Lista }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{{ url_for('home_bp.listar_elecciones') }}" class="btn btn-primary">Ir a Elecciones Activas</a>

{% endblock %}

app/templates/ProcesoVotacion/resumen.html
{% extends "base.html" %}
{% block title %}Resumen de votacion{% endblock %}
{% block content %}
<h1>Usted está realizando el siguiente voto:</h1>

<div class="container">
    <form id="votingForm" action="{{ url_for('home_bp.votar') }}" method="post">
        <div class="candidate">
            <div id="nombre-lista">
                <h5>{{ data.nombre }}</h5>
            </div>
        </div>
        <div class="option">
            <input type="hidden" name="id_lista" id="{{ data.id_lista }}" value="{{ data.id_lista }}">
        </div>
        <div id="cambiar-votar" class="mt-3">
            <input type="submit" class="btn btn-secondary" value="Confirmar Votacion">
        </div>
        <div class="mt-3">
            <a href="{{ url_for('home_bp.seleccionar_eleccion_votacion') }}" class="btn btn-primary">Cambiar votación</a>
        </div>
    </form>
</div>
{% endblock %}

app/templates/ProcesoVotacion/votacion.html
{% extends "base.html" %}
{% block title %}Detalles de la Elección{% endblock %}
{% block head %}
<style>
    body {
        background-color: #f0f0f0;
    }
    .container {
        margin-top: 50px;
        padding: 20px;
        background-color: #ffffff;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }
    .candidate {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 15px;
        border: 1px solid #007bff;
        border-radius: 10px;
        margin-bottom: 20px;
        transition: background-color 0.3s;
    }
    .candidate:hover {
        background-color: #e9ecef;
    }
    .candidate div {
        flex: 1;
        text-align: center;
    }
    .candidate img {
        max-width: 100px;
        border-radius: 50%;
    }
    .emitir-voto {
        background-color: #007bff;
        border-color: #007bff;
        color: white;
        padding: 10px 20px;
        width: 100%;
        border-radius: 10px;
        transition: background-color 0.3s, border-color 0.3s;
    }
    .emitir-voto:hover {
        background-color: #0056b3;
        border-color: #004085;
    }

</style>
{% endblock %}
{% block content %}
<body>
    <h3>Eliga a tu lista de preferencia:</h3>
    <div class="container">
        <form action="{{ url_for('home_bp.resumir_votacion') }}" method="post" id="votingForm">
            {% for lista in data %}
            <div class="candidate">
                <div id="nombre-lista">
                    <h5>{{ lista.nombre }} </h5>
                </div>
                <div id="nombre-partido">
                    <h5>Agrupacion politica</h5>
                    <p> {{ lista.id_lista }} </p>       
                </div>
                <div class="option">
                    <input type="radio" name="id_lista" id="{{ lista.id_lista }}" value="{{ lista.id_lista }}">
                </div>
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary emitir-voto">Votar</button>
            <a class="btn btn-primary emitir-voto" href="{{ url_for('home_bp.seleccionar_eleccion_votacion') }}" >Regresar</a>
        </form>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script>
        document.getElementById('votingForm').addEventListener('submit', function(event) {
            const radios = document.querySelectorAll('input[name="id_lista"]');
            let isChecked = false;
            radios.forEach(radio => {
                if (radio.checked) {
                    isChecked = true;
                }
            });
            if (!isChecked) {
                event.preventDefault();
                alert('Por favor seleccione una lista antes de continuar.');
            }
        });
    </script>
</body>

{% endblock %}

app/templates/ProcesoVotacion/votos.html
{% extends "base.html" %}
{% block title %}Detalles de los votos{% endblock %}

{% block content %}
    <h1>Detalles de los votos</h1>
    {% for eleccion in elecciones %}
        <h3>Votos de la lista {{ eleccion.descripcion }}</h3>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Cantidad Votos</th>
                </tr>
            </thead>
            <tbody>
                {% for votos in data[eleccion.id_eleccion] %}
                <tr>
                    <td>{{ votos.nombre_lista }}</td>
                    <td>{{ votos.cant_votos }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endfor %}
    <a href="{{ url_for('home_bp.home') }}" class="btn btn-primary">Ir a dashboard</a>
{% endblock %}