app/models/ListaCandidato.py
import enum

from sqlalchemy import Enum

from app import db
from app import ma

class EstadoListaEnum(enum.Enum):
    aprobado = "aprobado"
    desaprobado = "desaprobado"
    pendiente = "pendiente"

class ListaCandidato(db.Model):
    __tablename__ = 'lista_candidato'
    id_lista = db.Column(db.Integer, primary_key=True, autoincrement=True)
    nombre = db.Column(db.String(100), nullable=True)
    estado = db.Column(Enum(EstadoListaEnum), nullable=True, default=EstadoListaEnum.pendiente)
    id_eleccion = db.Column(db.Integer, db.ForeignKey('eleccion.id_eleccion'), nullable=True)
    propuestas = db.relationship('Propuesta', backref='lista_candidatol', lazy=True)
    candidatos = db.relationship('Candidato', backref='lista_candidatol', lazy=True)

    def __init__(self, nombre, id_eleccion, estado=EstadoListaEnum.pendiente):
        self.nombre = nombre
        self.id_eleccion = id_eleccion
        self.estado = estado
        
class ListaCandidatoSchema(ma.Schema):
    class Meta:
        fields = (
            'id_lista',
            'nombre',
            'estado',
            'id_lista'
        )

app/routes/routes.py
import logging
from functools import wraps
from flask import render_template, Blueprint, request, jsonify, session, redirect, url_for, make_response, flash, abort
from flask_login import login_user, logout_user, login_required, login_manager

from app.services.PersonaServicioImpl import ElectorServiceImpl
from app.services.EleccionServicioImpl import EleccionServicioImpl
from app.services.EleccionServicioImpl import ListaServicioImpl
from app.services.EleccionServicioImpl import CandidatoServicioImpl
from app.services.EleccionServicioImpl import VotoServicioImpl

from app.models.Elector import Elector
from app.models.Eleccion import Eleccion
from app.models.ListaCandidato import ListaCandidato
from app.models.Candidato import Candidato
from app.models.Propuesta import Propuesta

from functools import wraps
from app.services.PersonaServicioImpl import ElectorServiceImpl
from app.services.EleccionServicioImpl import EleccionServicioImpl


from dotenv import load_dotenv
import os

load_dotenv()

import bcrypt

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

REGISTER_TEMPLATE = 'register.html'

LOGIN_ROUTE = 'home_bp.login'

home_bp = Blueprint('home_bp', __name__, template_folder='templates')

elector_service = ElectorServiceImpl()
eleccion_servicio = EleccionServicioImpl()
lista_servicio = ListaServicioImpl()
candidato_servicio = CandidatoServicioImpl()
voto_servicio = VotoServicioImpl()

def admin_required(f):
    @wraps(f)
    def decorated_function_admin(*args, **kwargs):
        logger.info(f"Verificando acceso: sesión actual {session}")
        if not session.get('admin'):
            logger.info(f"Usuario no autorizado, sesión: {session}")
            return render_template("login.html")  
        return f(*args, **kwargs)
    return decorated_function_admin

@home_bp.route('/Admins')
@admin_required
def home():
    return render_template('Admin/home.html')


@home_bp.route('/ListaElecciones', methods=['GET'])
def mostrar_elecciones():
    eleccionesf = eleccion_servicio.get_elecciones_past()
    eleccionescurso = eleccion_servicio.get_elecciones_en_curso()
    eleccionespro = eleccion_servicio.get_elecciones_futuras()
    return render_template('General/elecciones.html', eleccionespro=eleccionespro, eleccionesf=eleccionesf, eleccionescurso=eleccionescurso)


@home_bp.route('/ListasCandidatos', methods=['GET'])
def listar_candidatos():
    listas_json = lista_servicio.obtener_listas()
    return render_template('ListaCandidato/lista_candidatos.html', listas=listas_json)

@home_bp.route('/aprobar_lista/<int:id_lista>', methods=['PUT'])
def aprobar_lista(id_lista):
    try:
        lista_servicio.aprobar_lista(id_lista)
        return jsonify({'message': 'Lista aprobada exitosamente'}), 200
    except Exception as e:
        logger.error(f'Error al aprobar la lista: {str(e)}')
        return jsonify({'message': 'Error al aprobar la lista', 'error': str(e)}), 500

@home_bp.route('/desaprobar_lista/<int:id_lista>', methods=['PUT'])
def desaprobar_lista(id_lista):
    try:
        lista_servicio.desaprobar_lista(id_lista)
        return jsonify({'message': 'Lista desaprobada exitosamente'}), 200
    except Exception as e:
        logger.error(f'Error al desaprobar la lista: {str(e)}')
        return jsonify({'message': 'Error al desaprobar la lista', 'error': str(e)}), 500

def login_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if 'correo' not in session:
            return redirect(url_for(LOGIN_ROUTE))
        return f(*args, **kwargs)
    return decorated_function


@home_bp.route('/ListasEleccionesVista', methods=['GET'])
def listar_candidatos_elector():
    listas = lista_servicio.obtener_listas_aprobadas()
    return render_template('ListaCandidato/listas_aprobadas.html', listas = listas)

@home_bp.route('/ListasElecciones', methods=['GET'])
def listas_candidatos_elector():
    listas = lista_servicio.obtener_listas_aprobadas()
    return render_template('ListaCandidato/listas_aprobadas.html', listas = listas)



@home_bp.route('/EleccionesActivas', methods=['GET'])
def listar_elecciones():
    elecciones_json = eleccion_servicio.get_all_eleccion()
    return render_template('lista_eleccion.html', elecciones = elecciones_json)


@home_bp.route('/candidatos/<int:id>', methods=['GET'])
def ver_lista_candidatos(id):
    listas_candidato = lista_servicio.get_lista_por_eleccion(id)

    if listas_candidato is None:
        abort(404)
    return render_template('ListaCandidato/lista_candidatos.html', listas=listas_candidato)

@home_bp.route('/VerListas', methods=['GET'])
def ver_candidatos():
    candidatos = candidato_servicio.get_candidatos_inscritos()
    return render_template("ListaCandidato/candidatos_inscritos.html", candidatos = candidatos)

@home_bp.route('/FormularioEleccion', methods=['GET'])
def agregar_eleccion():
    return render_template("ProcesoVotacion/form_eleccion.html")

@home_bp.route('/InsertEleccion', methods=['POST'])
def insert_eleccion():
    fecha = request.form['fecha']
    hora_inicio = request.form['hora_inicio']
    hora_fin = request.form['hora_fin']
    estado = request.form['estado']
    descripcion = request.form['descripcion']
    eleccion = Eleccion(fecha, hora_inicio, hora_fin, estado, descripcion)
    eleccion_servicio.insert_eleccion(eleccion)
    return url_for('home_bp.home')

@home_bp.route('/Votos')
def ver_votos():
    elecciones = eleccion_servicio.get_all_elecciones()
    votos = {}
    for eleccion in elecciones:
        votos[eleccion['id_eleccion']] = voto_servicio.get_cant_votos_by_eleccion(eleccion['id_eleccion'])
    print(len(votos))
    return render_template("ProcesoVotacion/votos.html", data = votos, elecciones = elecciones)


@home_bp.route('/EleccionVotacion', methods=['GET'])
@login_required
def seleccionar_eleccion_votacion():
    elector = elector_service.get_elector_by_email(session['correo'])
    elecciones = eleccion_servicio.get_elecciones_en_curso()
    elecciones_hechas = eleccion_servicio.get_elecciones_hechas_por_elector(elector.id)
    elecciones_restantes = len(elecciones) - len(elecciones_hechas)
    return render_template('ProcesoVotacion/lista_eleccion_votacion.html', \
                           data = elecciones, elecciones_hechas = elecciones_hechas, \
                            elecciones_restantes = elecciones_restantes)

@home_bp.route('/ListaVotacion', methods=['POST'])
@login_required
def ver_candidatos_votacion():
    id_eleccion = request.form['voto']
    candidatos = lista_servicio.get_lista_aprobada_by_eleccion(id_eleccion)
    print(candidatos)
    return render_template('ProcesoVotacion/votacion.html', data = candidatos)

@home_bp.route('/Resumen', methods=['POST'])
@login_required
def resumir_votacion():
    id_lista = request.form['id_lista']
    lista = lista_servicio.get_lista_by_id(id_lista)
    return render_template('ProcesoVotacion/resumen.html', data = lista)

@home_bp.route('/Votar', methods=['POST'])
@login_required
def votar():
    id_lista = request.form['id_lista']
    elector = elector_service.get_elector_by_email(session['correo'])
    voto_servicio.votar(id_lista, elector.id)
    return redirect(url_for('home_bp.dashboard'))

@home_bp.route('/')
def index():
    return render_template('index.html')

@home_bp.route('/register', methods=['GET','POST'])
def register():
    REGISTER_HTML = 'register.html'
    try:
        if request.method == 'POST':
            data = request.form
            elector = Elector(
                nombres=data.get('nombres'),
                apellido_paterno=data.get('apellido_paterno'),
                apellido_materno=data.get('apellido_materno'),
                fecha_nacimiento=data.get('fecha_nacimiento'),
                usuario=data.get('usuario'),
                contrasena=data.get('contrasena'),
                correo=data.get('correo')
            )

            elector_service.create_elector(elector,data.get('contrasena'))
            mensaje = 'Elector creado correctamente'
            return render_template(REGISTER_HTML, mensaje=mensaje)

        return render_template(REGISTER_HTML)
    except Exception as e:
        mensaje_error = f"Error al crear el elector: {str(e)}"
        logger.error(mensaje_error)
        return render_template(REGISTER_HTML, mensaje=mensaje_error)

@home_bp.route('/login', methods=['GET','POST'])
def login():
    LOGIN_HTML = 'login.html'
    try:
        if request.method == 'POST':
            data = request.form
            correo = data.get('correo')
            contrasena = data.get('contrasena')
            admin_email = os.getenv('ADMIN_EMAIL')
            admin_password = os.getenv('ADMIN_PASSWORD')
            if correo == admin_email and bcrypt.checkpw(contrasena.encode('utf-8'), admin_password.encode('utf-8')):
                session['correo'] = admin_email
                session['admin'] = True
                return render_template('Admin/home.html')
            elector = Elector.query.filter_by(correo=correo).first()
            if elector is None:
                mensaje = 'Correo o contraseña incorrectos'
                return render_template(LOGIN_HTML, mensaje=mensaje)
            if elector and elector.revisar_contrasena(contrasena):
                session['correo'] = elector.correo
                logger.info(f'El elector {elector.nombres} ha iniciado sesión')
                return render_template('dashboard.html', elector=elector)
            else:
                mensaje = 'Correo o contraseña incorrectos'
                return render_template(LOGIN_HTML, mensaje=mensaje)
        return render_template(LOGIN_HTML)
    except Exception as e:
        mensaje_error = f"Error al iniciar sesión: {str(e)}"
        logger.error(mensaje_error)
        return render_template(LOGIN_HTML, mensaje=mensaje_error)

@home_bp.route('/dashboard')
@login_required
def dashboard():
    if 'correo' in session:

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Cache-Control" content="no-store, no-cache, must-revalidate" />
    <meta http-equiv="Pragma" content="no-cache" />
    <meta http-equiv="Expires" content="0" />
    <title>{% block title %}Página de Inicio{% endblock %}</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    {% block head %}{% endblock %}

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{{ url_for('home_bp.index') }}">Elección Online</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('home_bp.index') }}">Home <span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('home_bp.register') }}">Registrate</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('home_bp.login') }}">Inicio Sesión</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('home_bp.listas_candidatos_elector') }}">Listas Candidatos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('home_bp.inscripcion_cand') }}">Inscripcion Candidatos</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container mt-4">
        {% block content %}{% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    {% block custom_scripts %}
    {% endblock %}
</body>

</html>

app/templates/dashboard.html
{% extends "base.html" %}

{% block title %}Welcome, {{ elector.nombres }}{% endblock %}

{% block content %}

<p>Hola, ¿Que tal el dia?</p>

<p>Nombre: {{ elector.nombres }}</p>
<p>Apellido: {{ elector.apellido_paterno }} {{ elector.apellido_materno }} </p>
<p>Correo: {{ elector.correo }}</p>

<a href="{{ url_for('home_bp.logout') }}">Logout</a>
<div class="text-center mt-4">
    <a href="{{ url_for('home_bp.seleccionar_eleccion_votacion') }}" class="btn btn-primary">Ir a votar</a>
</div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block title %}Página de Inicio{% endblock %}

{% block content %}
<div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="{{ url_for('static', filename='images/imagen1.png') }}" class="d-block w-100" alt="Urna de votación">
        </div>
        <div class="carousel-item">
            <img src="{{ url_for('static', filename='images/imagen2.jpg') }}" class="d-block w-100" alt="Fechas de las elecciones">
        </div>
    </div>
</div>

<!-- Botón para ir a votar -->
<div class="text-center mt-4">
    <a href="{{ url_for('home_bp.seleccionar_eleccion_votacion') }}" class="btn btn-primary">Ir a votar</a>
</div>
{% endblock %}

app/templates/inscripcion.html
{% extends "base.html" %}

{% block title %}Registro de Candidatos{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Registro de Candidatos</h5>
                    <form method="post" action="{{ url_for('home_bp.listas') }}">
                        <h6>Presidente</h6>
                        <div class="form-group">
                            <label for="nombre{{ 0}}">Nombre</label>
                            <input type="text" class="form-control" id="nombre{{ 0 }}" name="nombre{{ 0 }}">
                        </div>
                        <div class="form-group">
                            <label for="apellido_paterno{{ 0 }}">Apellido Paterno</label>
                            <input type="text" class="form-control" id="apellido_paterno{{ 0 }}" name="apellido_paterno{{ 0 }}">
                        </div>
                        <div class="form-group">
                            <label for="apellido_materno{{ 0 }}">Apellido Materno</label>
                            <input type="text" class="form-control" id="apellido_materno{{ 0 }}" name="apellido_materno{{ 0 }}">
                        </div>
                        <hr>
                        {% for i in range(1,4) %}
                        <h6>Candidato {{ i }}</h6>
                        <div class="form-group">
                            <label for="nombre{{ i }}">Nombre</label>
                            <input type="text" class="form-control" id="nombre{{ i }}" name="nombre{{ i }}">
                        </div>
                        <div class="form-group">
                            <label for="apellido_paterno{{ i }}">Apellido Paterno</label>
                            <input type="text" class="form-control" id="apellido_paterno{{ i }}" name="apellido_paterno{{ i }}">
                        </div>
                        <div class="form-group">
                            <label for="apellido_materno{{ i }}">Apellido Materno</label>
                            <input type="text" class="form-control" id="apellido_materno{{ i }}" name="apellido_materno{{ i }}">
                        </div>
                        <hr>
                        {% endfor %}
                        
                        <div class="form-group">
                            <label for="nombre_partido">Nombre del Partido</label>
                            <input type="text" class="form-control" id="nombre_partido" name="nombre_partido">
                        </div>

                        <div class="form-group">
                            <label for="" >Propuestas</label>
                            <div id="propuestas-container">
                                <div class="input-group mb-3">
                                    <input type="text" class="form-control" name="propuestas[]" placeholder="Propuesta">
                                    <div class="input-group-append">
                                        <button class="btn btn-outline-secondary" type="button" onclick="agregarPropuesta()">Añadir</button>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="campana">Campaña Electoral</label>
                            <select class="form-control" id="campana" name="camapana" >
                                <option value="">Seleccione una elección</option>
                                {% for eleccion in elecciones %}
                                    <option value="{{eleccion.id_eleccion}}">{{ eleccion.descripcion }}</option>
                                {% endfor %}
                            </select>
                        </div>

                        <button type="submit" class="btn btn-primary">Registrar Candidatos</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block custom_scripts %}
<script src="{{ url_for('static', filename='js/scripts.js') }}"></script>

{% if mensaje %}
<script>
    mostrarMensaje("{{ mensaje | escape }}");
</script>

{% endif %}
{% endblock %}

app/templates/lista_candidatos.html
{% extends "base.html" %}
{% block title %}Detalles de la Elección{% endblock %}

{% block content %}
    <h2>Candidatos</h2>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Candidato</th>
                <th>Lista</th>
            </tr>
        </thead>
        <tbody>
            {% for candidato in data %}
            <tr>
                <td>{{ candidato.Candidato }}</td>
                <td>{{ candidato.Lista }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{{ url_for('home_bp.listar_elecciones') }}" class="btn btn-primary">Ir a Elecciones Activas</a>

{% endblock %}

app/templates/lista_eleccion.html
{% extends "base.html" %}
{% block title %}Listas de Elecciones activas{% endblock %}

{% block content %}
    <h1>Lista de Elecciones</h1>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>ID</th>
                <th>Fecha</th>
                <th>Hora</th>
                <th>Descripcion</th>
            </tr>
        </thead>
        <tbody>
            {% for eleccion in elecciones %}
            <tr>
                <td>{{ eleccion.id_eleccion }}</td>
                <td>{{ eleccion.fecha }}</td>
                <td>{{ eleccion.hora_inicio }} - {{ eleccion.hora_fin }}</td>
                <td>{{ eleccion.descripcion }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock %}

app/templates/listas_candidatas.html
{% extends "base.html" %}
{% block title %}Detalles de la Elección{% endblock %}

{% block content %}
    <h2>Candidatos</h2>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Candidato</th>
                <th>Lista</th>
            </tr>
        </thead>
        <tbody>
            {% for candidato in data %}
            <tr>
                <td>{{ candidato.Candidato }}</td>
                <td>{{ candidato.Lista }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{{ url_for('home_bp.listar_elecciones') }}" class="btn btn-primary">Ir a Elecciones Activas</a>

{% endblock %}

app/templates/login.html
{% extends "base.html" %}

{% block title %}Iniciar Sesión{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Iniciar Sesión</h5>
                    <form method="post" action="{{ url_for('home_bp.login') }}">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Correo Electrónico</label>
                            <input type="email" class="form-control" id="exampleInputEmail1"
                                aria-describedby="emailHelp" name="correo">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1">Contraseña</label>
                            <input type="password" class="form-control" id="exampleInputPassword1" name="contrasena">
                        </div>
                        <button type="submit" class="btn btn-primary">Iniciar Sesión</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block custom_scripts %}
{% if mensaje %}
<script>
    alert("{{ mensaje | escape }}");
</script>
{% endif %}
{% endblock %}

app/templates/register.html
{% extends "base.html" %}

{% block title %}Registro{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Registro</h5>
                    <form method="POST" action="{{ url_for('home_bp.register') }}">
                        <!-- Nombres -->
                        <div class="form-group">
                            <label for="inputNombres">Nombres</label>
                            <input type="text" class="form-control" id="inputNombres" name="nombres" required>
                        </div>
                        <!-- Apellido Paterno -->
                        <div class="form-group">
                            <label for="inputApellidoPaterno">Apellido Paterno</label>
                            <input type="text" class="form-control" id="inputApellidoPaterno" name="apellido_paterno"
                                required>
                        </div>
                        <!-- Apellido Materno -->
                        <div class="form-group">
                            <label for="inputApellidoMaterno">Apellido Materno</label>
                            <input type="text" class="form-control" id="inputApellidoMaterno" name="apellido_materno"
                                required>
                        </div>
                        <!-- Fecha de Nacimiento -->
                        <div class="form-group">
                            <label for="inputFechaNacimiento">Fecha de Nacimiento</label>
                            <input type="date" class="form-control" id="inputFechaNacimiento" name="fecha_nacimiento"
                                required>
                        </div>
                        <!-- Usuario -->
                        <div class="form-group">
                            <label for="inputUsuario">Usuario</label>
                            <input type="text" class="form-control" id="inputUsuario" name="usuario" required>
                        </div>
                        <!-- Correo -->
                        <div class="form-group">
                            <label for="inputCorreo">Correo</label>
                            <input type="email" class="form-control" id="inputCorreo" name="correo" required>
                        </div>
                        <!-- Contraseña -->
                        <div class="form-group">
                            <label for="inputContrasena">Contraseña</label>
                            <input type="password" class="form-control" id="inputContrasena" name="contrasena" required>
                        </div>
                        <!-- Botón de registro -->
                        <button type="submit" class="btn btn-success">Registrarse</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% if mensaje %}
        <input type="hidden" id="mensaje" value="{{ mensaje | escape }}">
    {% endif %}
</div>
{% endblock %}

{% block custom_scripts %}
    <script src="{{ url_for('static', filename='js/scripts.js') }}"></script>
{% endblock %}